window.TMLB_DATA = [
    {
      id:'radioml2018', name:'RadioML 2018.01A', category:'Modulation Classification',
      taskType:'Automatic Modulation Classification', mlType:'Classification · 24-class',
      description:'Synthetic and over-the-air RF recordings spanning 24 digital and analog modulation schemes across SNRs from −20 to +30 dB — the de facto benchmark for AMC.',
      taskDef:'Classify the modulation scheme of a 1024-sample complex IQ waveform. Models are scored by mean classification accuracy across all SNR levels in the held-out test split.',
      metric:'Accuracy (all-SNR)', decimals:1, suffix:'%', higherIsBetter:true,
      accessLink:'https://www.deepsig.ai/datasets',
      features:{ samples:'2,555,904', split:'70 / 10 / 20', format:'HDF5 → X.npy, y.npy', size:'≈ 20 GB',
        columns:['X · (1024,2)','y','snr'],
        rows:[
          ['[[-0.031,  0.112], …]','16QAM','18'],
          ['[[ 0.418, -0.176], …]','BPSK','−4'],
          ['[[ 0.073,  0.051], …]','QPSK','30'],
          ['[[-0.512,  0.224], …]','AM-DSB','6'],
          ['[[ 0.129, -0.087], …]','GFSK','−12'],
        ],
        dist:{ train:{rows:'1,789,132', size:'14.0 GB'}, val:{rows:'255,590', size:'2.0 GB'}, test:{rows:'511,182', size:'4.0 GB'},
          subFile:'submission.csv', subLines:['id,modulation','0,16QAM','1,BPSK','2,QPSK','…'] }},
      submissions:[
        {id:'rml-base', source:'baseline', paperTitle:'VT-CNN2 (reference baseline)', authors:"NextGLabs", paperLink:'https://arxiv.org/abs/1712.04578', codeLink:'https://github.com/radioML/examples', claimedScore:null, score:53.1, reproStatus:'n/a', reproLink:null, date:'2018-07-01'},
        {id:'rml-auth', source:'author_submitted', paperTitle:'X-Mod: A Transformer for Modulation Recognition', authors:'Vural, Tanaka, Greco', paperLink:'https://arxiv.org/abs/2403.11210', codeLink:'https://github.com/xmod-lab/xmod', claimedScore:64.2, score:63.8, reproStatus:'n/a', reproLink:null, date:'2024-03-18'},
        {id:'rml-r1', source:'ai_reproduced', paperTitle:'ResNet-1D for Robust Modulation Classification', authors:'Petrov, Singh', paperLink:'https://arxiv.org/abs/2210.04412', codeLink:'https://github.com/petrov/resnet1d-amc', claimedScore:61.5, score:60.2, reproStatus:'success', reproLink:'#', date:'2025-02-04', note:'Re-implemented the 1D residual stack directly from the architecture table and trained 80 epochs on the canonical split with the paper’s Adam schedule. Reproduced within 1.3 points of the reported all-SNR accuracy — a faithful match.'},
        {id:'rml-r2', source:'ai_reproduced', paperTitle:'Hierarchical Attention for Few-Sample AMC', authors:'Nakamura, Brandt, Liu', paperLink:'https://arxiv.org/abs/2305.09981', codeLink:'https://github.com/hattn/hier-amc', claimedScore:72.0, score:58.4, reproStatus:'partial', reproLink:'#', date:'2025-02-09', note:'The attention architecture reproduced faithfully, but the paper’s 72% depends on an undocumented per-SNR test-time calibration step that is not in the released code. Without it the model lands at 58.4% — a 13.6-point shortfall we report honestly rather than papering over.'},
        {id:'rml-r3', source:'ai_reproduced', paperTitle:'GAN-Augmented Few-Shot AMC', authors:'Okonkwo, Ferreira', paperLink:'https://arxiv.org/abs/2401.07733', codeLink:'https://github.com/ganamc/fewshot', claimedScore:69.0, score:null, reproStatus:'failed', reproLink:'#', date:'2025-02-11', note:'Reproduction blocked: the released GAN checkpoint format is incompatible with the described generator, and no training recipe for the augmenter is provided. We could not produce a held-out test number, so no score is ranked.'},
      ]
    },
    {
      id:'csinet-cost2100', name:'CSI Feedback — COST2100 Indoor', category:'CSI Feedback',
      taskType:'Massive-MIMO CSI Compression & Feedback', mlType:'Regression · reconstruction',
      description:'COST2100 indoor channel matrices at 5.3 GHz, the standard benchmark for deep CSI feedback — compressing the downlink channel for low-overhead uplink reporting.',
      taskDef:'Compress a 32×32 complex CSI matrix to a low-dimensional codeword and reconstruct it at the base station. Scored as NMSE in dB at a 1/4 compression ratio — lower is better.',
      metric:'NMSE @ 1/4 (dB)', decimals:1, suffix:' dB', higherIsBetter:false,
      accessLink:'https://github.com/sydney222/Python_CsiNet',
      features:{ samples:'150,000', split:'100k / 30k / 20k', format:'.mat (v7.3) → X.npy', size:'≈ 1.2 GB',
        columns:['X · (2,32,32)','y · (2,32,32)','ratio'],
        rows:[
          ['[[[ 0.84, -0.12], …]]','[[[ 0.83, -0.11], …]]','1/4'],
          ['[[[-0.21,  0.55], …]]','[[[-0.20,  0.52], …]]','1/8'],
          ['[[[ 0.07,  0.31], …]]','[[[ 0.07,  0.29], …]]','1/4'],
          ['[[[ 0.44, -0.38], …]]','[[[ 0.41, -0.33], …]]','1/16'],
          ['[[[-0.09,  0.16], …]]','[[[-0.08,  0.14], …]]','1/32'],
        ],
        dist:{ train:{rows:'100,000', size:'820 MB'}, val:{rows:'30,000', size:'246 MB'}, test:{rows:'20,000', size:'164 MB'},
          subFile:'submission.npy', subLines:['# shape (20000, 2, 32, 32)','# reconstructed CSI per test id','# scored as NMSE (dB)'] }},
      submissions:[
        {id:'csi-base', source:'baseline', paperTitle:'CsiNet (reference baseline)', authors:'NextGLabs', paperLink:'https://arxiv.org/abs/1712.08919', codeLink:'https://github.com/sydney222/Python_CsiNet', claimedScore:null, score:-8.7, reproStatus:'n/a', reproLink:null, date:'2018-03-01'},
        {id:'csi-auth', source:'author_submitted', paperTitle:'CRNet: Multi-Resolution CSI Feedback', authors:'Lu, Wang, Hu', paperLink:'https://arxiv.org/abs/1910.14322', codeLink:'https://github.com/Kylin9511/CRNet', claimedScore:-11.4, score:-11.1, reproStatus:'n/a', reproLink:null, date:'2023-09-22'},
        {id:'csi-r1', source:'ai_reproduced', paperTitle:'CsiNet+: Refined CSI Reconstruction', authors:'Guo, Wen, Jin', paperLink:'https://arxiv.org/abs/1906.06007', codeLink:'https://github.com/csinetplus/repo', claimedScore:-12.7, score:-12.0, reproStatus:'success', reproLink:'#', date:'2025-01-28', note:'Built the refinement decoder from the paper spec and trained on the canonical COST2100 indoor split with deterministic seeds. Reproduced −12.0 dB against the claimed −12.7 dB — a faithful, close match within run-to-run variance.'},
        {id:'csi-r2', source:'ai_reproduced', paperTitle:'TransNet: Attention-Based CSI Feedback', authors:'Cui, Guo, Wen', paperLink:'https://arxiv.org/abs/2110.09438', codeLink:'https://github.com/transnet-csi/code', claimedScore:-17.4, score:-9.6, reproStatus:'partial', reproLink:'#', date:'2025-02-02', note:'The transformer reproduced cleanly, but the reported −17.4 dB assumes a 1/16 ratio in one table that the abstract presents as the headline number. Evaluated apples-to-apples at the 1/4 ratio used by every other entry here, it reaches −9.6 dB. The gap is a conditions mismatch in the paper, not a reproduction failure.'},
        {id:'csi-r3', source:'ai_reproduced', paperTitle:'Diffusion-CSI: Generative Channel Recovery', authors:'Abadi, Lindqvist', paperLink:'https://arxiv.org/abs/2402.01188', codeLink:'https://github.com/diff-csi/repo', claimedScore:-19.2, score:null, reproStatus:'failed', reproLink:'#', date:'2025-02-06', note:'Reproduction blocked: the diffusion sampler requires a pretrained prior that is referenced but not released, and training it from scratch diverges under the documented hyperparameters. No held-out number could be produced.'},
      ]
    },
    {
      id:'deepsense-6g', name:'DeepSense 6G — Blockage Prediction', category:'Beam & Blockage Prediction',
      taskType:'Multimodal Proactive Blockage Prediction', mlType:'Classification · binary',
      description:'Real-world co-located camera, LiDAR, radar, GPS and mmWave beam measurements. The blockage-prediction split asks models to foresee an imminent link blockage from sensor context.',
      taskDef:'Given a short window of multimodal sensor inputs, predict whether the mmWave link will be blocked within the next interval. Scored as F1 on held-out test scenarios — higher is better.',
      metric:'F1 score', decimals:2, suffix:'', higherIsBetter:true,
      accessLink:'https://deepsense6g.net',
      features:{ samples:'30,176 sequences', split:'by scenario', format:'per-modality folders + manifest.json', size:'≈ 120 GB',
        columns:['rgb','lidar','radar','beams','y'],
        rows:[
          ['⟨960×540×3⟩','⟨7421×3⟩','⟨64×64⟩','[0.02, 0.14, …]','0'],
          ['⟨960×540×3⟩','⟨7188×3⟩','⟨64×64⟩','[0.05, 0.31, …]','1'],
          ['⟨960×540×3⟩','⟨7602×3⟩','⟨64×64⟩','[0.01, 0.08, …]','0'],
          ['⟨960×540×3⟩','⟨7045×3⟩','⟨64×64⟩','[0.09, 0.42, …]','1'],
          ['⟨960×540×3⟩','⟨7333×3⟩','⟨64×64⟩','[0.03, 0.11, …]','0'],
        ],
        dist:{ train:{rows:'21,000 seq', size:'84 GB'}, val:{rows:'4,500 seq', size:'18 GB'}, test:{rows:'4,676 seq', size:'18 GB'},
          subFile:'submission.csv', subLines:['id,blockage','0,0','1,1','2,0','…'] }},
      submissions:[
        {id:'ds-base', source:'baseline', paperTitle:'GRU Sensor-Fusion (reference baseline)', authors:'NextGLabs', paperLink:'https://arxiv.org/abs/2211.09769', codeLink:'https://github.com/DeepSense6G/baseline', claimedScore:null, score:0.49, reproStatus:'n/a', reproLink:null, date:'2022-11-01'},
        {id:'ds-auth', source:'author_submitted', paperTitle:'Multimodal Beam Net for Proactive Hand-off', authors:'Charan, Demirhan', paperLink:'https://arxiv.org/abs/2305.07729', codeLink:'https://github.com/mbn-6g/repo', claimedScore:0.58, score:0.56, reproStatus:'n/a', reproLink:null, date:'2024-06-14'},
        {id:'ds-r1', source:'ai_reproduced', paperTitle:'LiDAR-Aided Blockage Forecasting', authors:'Wu, Osman', paperLink:'https://arxiv.org/abs/2306.10544', codeLink:'https://github.com/lidar-block/repo', claimedScore:0.54, score:0.52, reproStatus:'success', reproLink:'#', date:'2025-01-31', note:'Fused the LiDAR voxel encoder with the beam-power sequence per the paper and trained on the canonical scenarios split. Reached 0.52 F1 against the claimed 0.54 — a faithful, honest reproduction.'},
        {id:'ds-r2', source:'ai_reproduced', paperTitle:'RGB-Radar Fusion for Blockage Prediction', authors:'Park, Halevi', paperLink:'https://arxiv.org/abs/2309.04471', codeLink:'https://github.com/rgb-radar/repo', claimedScore:0.55, score:0.94, reproStatus:'success', reproLink:'#', date:'2025-02-03', flag:'suspect', note:'Flagged suspect. The pipeline scores 0.94 F1 — far above the claimed 0.55 — because the naive temporal window leaks future frames that already contain the blockage event into the input. The model is effectively reading the answer. A real win over a published number by this margin almost always means leakage or a trivialized task, so we mark it rather than crown it.'},
        {id:'ds-r3', source:'ai_reproduced', paperTitle:'Event-Camera Blockage Anticipation', authors:'Sørensen, Mehta', paperLink:'https://arxiv.org/abs/2401.15522', codeLink:'https://github.com/evcam-block/repo', claimedScore:0.61, score:null, reproStatus:'failed', reproLink:'#', date:'2025-02-08', note:'Reproduction blocked: the event-camera modality is not included in the public DeepSense release, and the paper’s preprocessing for it is unspecified. The task cannot be reconstructed from available data.'},
      ]
    },
    {
      id:'radiomapseer', name:'RadioMapSeer — Path-Loss Estimation', category:'Radio-Map Estimation',
      taskType:'Radio-Map / Path-Loss Estimation', mlType:'Regression · dense / image-to-image',
      description:'Large-scale simulated urban radio maps pairing city geometry with ground-truth path-loss fields, used to benchmark learned radio-map estimators against ray-tracing references.',
      taskDef:'Predict the dense path-loss map for a transmitter given building layout and sparse measurements. Scored as RMSE in dB over the test cities — lower is better.',
      metric:'RMSE (dB)', decimals:2, suffix:' dB', higherIsBetter:false,
      accessLink:'https://radiomapseer.github.io',
      features:{ samples:'56,000 maps', split:'600 / 50 / 50 cities', format:'PNG → X.npy, y.npy', size:'≈ 8 GB',
        columns:['X · (256,256,2)','y · (256,256)','tx'],
        rows:[
          ['⟨256×256×2⟩','[[101.4, 103.8], …]','[ 64, 128]'],
          ['⟨256×256×2⟩','[[ 96.2,  98.0], …]','[200,  41]'],
          ['⟨256×256×2⟩','[[112.7, 115.1], …]','[ 18, 174]'],
          ['⟨256×256×2⟩','[[ 88.5,  90.3], …]','[133, 220]'],
          ['⟨256×256×2⟩','[[104.9, 107.2], …]','[ 71,  12]'],
        ],
        dist:{ train:{rows:'48,000 maps', size:'6.8 GB'}, val:{rows:'4,000 maps', size:'0.6 GB'}, test:{rows:'4,000 maps', size:'0.6 GB'},
          subFile:'submission.npy', subLines:['# shape (4000, 256, 256)','# predicted path-loss map per test id','# scored as RMSE (dB)'] }},
      submissions:[
        {id:'rm-base', source:'baseline', paperTitle:'RadioUNet (reference baseline)', authors:'NextGLabs', paperLink:'https://arxiv.org/abs/1911.09002', codeLink:'https://github.com/RonLevie/RadioUNet', claimedScore:null, score:4.60, reproStatus:'n/a', reproLink:null, date:'2021-02-01'},
        {id:'rm-auth', source:'author_submitted', paperTitle:'PMNet: Pixel-wise Path-loss Map Estimation', authors:'Lee, Bhattacharya', paperLink:'https://arxiv.org/abs/2211.10527', codeLink:'https://github.com/pmnet/repo', claimedScore:4.10, score:4.22, reproStatus:'n/a', reproLink:null, date:'2024-02-19'},
        {id:'rm-r1', source:'ai_reproduced', paperTitle:'RME-GAN: Adversarial Radio-Map Estimation', authors:'Zhang, Achterberg', paperLink:'https://arxiv.org/abs/2212.12817', codeLink:'https://github.com/rme-gan/repo', claimedScore:5.00, score:5.31, reproStatus:'success', reproLink:'#', date:'2025-01-25', note:'Trained the generator/discriminator pair on the canonical RadioMapSeer split. Landed at 5.31 dB RMSE against the claimed 5.00 dB — slightly behind but faithful to the task and within reasonable variance.'},
        {id:'rm-r2', source:'ai_reproduced', paperTitle:'FastRadioMap: Lightweight Path-Loss Net', authors:'Ibrahimović, Tan', paperLink:'https://arxiv.org/abs/2310.06621', codeLink:'https://github.com/fastradiomap/repo', claimedScore:6.62, score:0.23, reproStatus:'success', reproLink:'#', date:'2025-02-05', flag:'suspect', note:'Flagged suspect. The reproduction reports 0.23 dB RMSE against the paper’s 6.62 dB — a 28× “improvement.” On inspection the canonical input tensor contains the sampled ground-truth path-loss values the model is asked to predict, so it trivially copies them. This is a leaking representation, not a real result. A naïve leaderboard would have published this as state-of-the-art; we flag it instead.'},
        {id:'rm-r3', source:'ai_reproduced', paperTitle:'NeRF-Radio: Neural Field Radio Maps', authors:'Okafor, Reuben', paperLink:'https://arxiv.org/abs/2403.09981', codeLink:'https://github.com/nerf-radio/repo', claimedScore:3.80, score:null, reproStatus:'failed', reproLink:'#', date:'2025-02-10', note:'Reproduction blocked: the neural-field encoder expects per-ray geometry that is gated behind a separate terms-acceptance form not satisfiable automatically. Data could not be canonicalized, so no number was produced.'},
      ]
    },
  ];
